// Generated by Wrangler by running `wrangler types src/worker-configuration.d.ts`

interface Env {
	STATUS_KV: KVNamespace;
	RESEND_API_KEY: string;
	FEIDE_CLIENT_ID: string;
	FEIDE_CLIENT_SECRET: string;
	FEIDE_REDIRECT_URI: string;
	DB: D1Database;
}
