version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
minio:
    image: quay.io/minio/minio
    restart: always
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio:/data
    command: server /data --console-address ":9001"

volumes:
  postgres:
    driver: local
  minio:
    driver: local
