packages:
  - programmerbar-cms
  - programmerbar-email-templates
  - programmerbar-web

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@openapitools/openapi-generator-cli'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - workerd
