packages:
  - programmerbar-cms
  - programmerbar-email-templates
  - programmerbar-web

# Only install packages that has been out for 7 days. This is to prevent
# install potentially harmful pacakges. There have been numerous cases
# where this has happened with npm.
minimumReleaseAge: 10080

# Only allow these packages to run post-build scripts. Having unknown/sketchy
# packages run custom scripts is a security vulnerability and should be
# avoided.
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
