// Generated by Wrangler on Thu Oct 10 2024 10:10:43 GMT+0200 (Central European Summer Time)
// by running `wrangler types worker-configuration.d.ts`

interface Env {
  FEEDBACK_KV: KVNamespace;
  RESEND_API_KEY: string;
}
