/* tslint:disable */
/* eslint-disable */
/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { GenericResponseHashMapStringString } from '../models/index';
import {
	GenericResponseHashMapStringStringFromJSON,
	GenericResponseHashMapStringStringToJSON
} from '../models/index';

/**
 *
 */
export class AdminApi extends runtime.BaseAPI {
	/**
	 * Test endpoint to verify it checks the admin key
	 */
	async adminTestRaw(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<GenericResponseHashMapStringString>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		if (this.configuration && this.configuration.accessToken) {
			const token = this.configuration.accessToken;
			const tokenString = await token('admin_key', []);

			if (tokenString) {
				headerParameters['Authorization'] = `Bearer ${tokenString}`;
			}
		}

		let urlPath = `/admin`;

		const response = await this.request(
			{
				path: urlPath,
				method: 'GET',
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) =>
			GenericResponseHashMapStringStringFromJSON(jsonValue)
		);
	}

	/**
	 * Test endpoint to verify it checks the admin key
	 */
	async adminTest(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<GenericResponseHashMapStringString> {
		const response = await this.adminTestRaw(initOverrides);
		return await response.value();
	}
}
