/* tslint:disable */
/* eslint-disable */
/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { HealthResponse } from '../models/index';
import { HealthResponseFromJSON, HealthResponseToJSON } from '../models/index';

/**
 *
 */
export class HealthApi extends runtime.BaseAPI {
	/**
	 * Returns a simple health check response indicating that the API is running. This endpoint is typically used by monitoring systems and load balancers.
	 * Check the health status of the API.
	 */
	async healthRaw(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<runtime.ApiResponse<HealthResponse>> {
		const queryParameters: any = {};

		const headerParameters: runtime.HTTPHeaders = {};

		let urlPath = `/health`;

		const response = await this.request(
			{
				path: urlPath,
				method: 'GET',
				headers: headerParameters,
				query: queryParameters
			},
			initOverrides
		);

		return new runtime.JSONApiResponse(response, (jsonValue) => HealthResponseFromJSON(jsonValue));
	}

	/**
	 * Returns a simple health check response indicating that the API is running. This endpoint is typically used by monitoring systems and load balancers.
	 * Check the health status of the API.
	 */
	async health(
		initOverrides?: RequestInit | runtime.InitOverrideFunction
	): Promise<HealthResponse> {
		const response = await this.healthRaw(initOverrides);
		return await response.value();
	}
}
