/* tslint:disable */
/* eslint-disable */
/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface EventUser
 */
export interface EventUser {
	/**
	 * Email address of the user
	 * @type {string}
	 * @memberof EventUser
	 */
	email: string;
	/**
	 * Unique identifier for the user
	 * @type {string}
	 * @memberof EventUser
	 */
	id: string;
	/**
	 * Name of the user
	 * @type {string}
	 * @memberof EventUser
	 */
	name: string;
}

/**
 * Check if a given object implements the EventUser interface.
 */
export function instanceOfEventUser(value: object): value is EventUser {
	if (!('email' in value) || value['email'] === undefined) return false;
	if (!('id' in value) || value['id'] === undefined) return false;
	if (!('name' in value) || value['name'] === undefined) return false;
	return true;
}

export function EventUserFromJSON(json: any): EventUser {
	return EventUserFromJSONTyped(json, false);
}

export function EventUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventUser {
	if (json == null) {
		return json;
	}
	return {
		email: json['email'],
		id: json['id'],
		name: json['name']
	};
}

export function EventUserToJSON(json: any): EventUser {
	return EventUserToJSONTyped(json, false);
}

export function EventUserToJSONTyped(
	value?: EventUser | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		email: value['email'],
		id: value['id'],
		name: value['name']
	};
}
