/* tslint:disable */
/* eslint-disable */
/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface FullProduct
 */
export interface FullProduct {
	/**
	 * Alcohol content of the product, if applicable
	 * @type {number}
	 * @memberof FullProduct
	 */
	alcoholContent?: number | null;
	/**
	 * Timestamp when the product was created
	 * @type {Date}
	 * @memberof FullProduct
	 */
	createdAt: Date;
	/**
	 * Credits needed to claim the product internally
	 * @type {number}
	 * @memberof FullProduct
	 */
	credits?: number | null;
	/**
	 * Description of the product
	 * @type {string}
	 * @memberof FullProduct
	 */
	description?: string | null;
	/**
	 * Unique identifier for the product
	 * @type {string}
	 * @memberof FullProduct
	 */
	id: string;
	/**
	 * Image ID associated with the product, if any
	 * @type {string}
	 * @memberof FullProduct
	 */
	imageId?: string | null;
	/**
	 * Internal price for the product
	 * @type {number}
	 * @memberof FullProduct
	 */
	internalPrice: number;
	/**
	 * Indicates if the product is sold out
	 * @type {boolean}
	 * @memberof FullProduct
	 */
	isSoldOut: boolean;
	/**
	 * Name of the product
	 * @type {string}
	 * @memberof FullProduct
	 */
	name: string;
	/**
	 * Price for ordinary customers
	 * @type {number}
	 * @memberof FullProduct
	 */
	ordinaryPrice: number;
	/**
	 * ID of the producer, if applicable
	 * @type {string}
	 * @memberof FullProduct
	 */
	producerId?: string | null;
	/**
	 * Stock keeping unit for the product
	 * @type {string}
	 * @memberof FullProduct
	 */
	sku?: string | null;
	/**
	 * Price for students
	 * @type {number}
	 * @memberof FullProduct
	 */
	studentPrice: number;
	/**
	 * Timestamp when the product was last updated
	 * @type {Date}
	 * @memberof FullProduct
	 */
	updatedAt: Date;
	/**
	 * Variants of the product, if applicable
	 * @type {string}
	 * @memberof FullProduct
	 */
	variants?: string | null;
	/**
	 * Volume of the product, if applicable
	 * @type {number}
	 * @memberof FullProduct
	 */
	volume?: number | null;
}

/**
 * Check if a given object implements the FullProduct interface.
 */
export function instanceOfFullProduct(value: object): value is FullProduct {
	if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
	if (!('id' in value) || value['id'] === undefined) return false;
	if (!('internalPrice' in value) || value['internalPrice'] === undefined) return false;
	if (!('isSoldOut' in value) || value['isSoldOut'] === undefined) return false;
	if (!('name' in value) || value['name'] === undefined) return false;
	if (!('ordinaryPrice' in value) || value['ordinaryPrice'] === undefined) return false;
	if (!('studentPrice' in value) || value['studentPrice'] === undefined) return false;
	if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
	return true;
}

export function FullProductFromJSON(json: any): FullProduct {
	return FullProductFromJSONTyped(json, false);
}

export function FullProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): FullProduct {
	if (json == null) {
		return json;
	}
	return {
		alcoholContent: json['alcohol_content'] == null ? undefined : json['alcohol_content'],
		createdAt: new Date(json['created_at']),
		credits: json['credits'] == null ? undefined : json['credits'],
		description: json['description'] == null ? undefined : json['description'],
		id: json['id'],
		imageId: json['image_id'] == null ? undefined : json['image_id'],
		internalPrice: json['internal_price'],
		isSoldOut: json['is_sold_out'],
		name: json['name'],
		ordinaryPrice: json['ordinary_price'],
		producerId: json['producer_id'] == null ? undefined : json['producer_id'],
		sku: json['sku'] == null ? undefined : json['sku'],
		studentPrice: json['student_price'],
		updatedAt: new Date(json['updated_at']),
		variants: json['variants'] == null ? undefined : json['variants'],
		volume: json['volume'] == null ? undefined : json['volume']
	};
}

export function FullProductToJSON(json: any): FullProduct {
	return FullProductToJSONTyped(json, false);
}

export function FullProductToJSONTyped(
	value?: FullProduct | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		alcohol_content: value['alcoholContent'],
		created_at: value['createdAt'].toISOString(),
		credits: value['credits'],
		description: value['description'],
		id: value['id'],
		image_id: value['imageId'],
		internal_price: value['internalPrice'],
		is_sold_out: value['isSoldOut'],
		name: value['name'],
		ordinary_price: value['ordinaryPrice'],
		producer_id: value['producerId'],
		sku: value['sku'],
		student_price: value['studentPrice'],
		updated_at: value['updatedAt'].toISOString(),
		variants: value['variants'],
		volume: value['volume']
	};
}
