/* tslint:disable */
/* eslint-disable */
/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GenericResponseHashMapStringString
 */
export interface GenericResponseHashMapStringString {
	/**
	 *
	 * @type {{ [key: string]: string; }}
	 * @memberof GenericResponseHashMapStringString
	 */
	data?: { [key: string]: string };
	/**
	 * Indicates whether the request was successful
	 * @type {boolean}
	 * @memberof GenericResponseHashMapStringString
	 */
	success: boolean;
}

/**
 * Check if a given object implements the GenericResponseHashMapStringString interface.
 */
export function instanceOfGenericResponseHashMapStringString(
	value: object
): value is GenericResponseHashMapStringString {
	if (!('success' in value) || value['success'] === undefined) return false;
	return true;
}

export function GenericResponseHashMapStringStringFromJSON(
	json: any
): GenericResponseHashMapStringString {
	return GenericResponseHashMapStringStringFromJSONTyped(json, false);
}

export function GenericResponseHashMapStringStringFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): GenericResponseHashMapStringString {
	if (json == null) {
		return json;
	}
	return {
		data: json['data'] == null ? undefined : json['data'],
		success: json['success']
	};
}

export function GenericResponseHashMapStringStringToJSON(
	json: any
): GenericResponseHashMapStringString {
	return GenericResponseHashMapStringStringToJSONTyped(json, false);
}

export function GenericResponseHashMapStringStringToJSONTyped(
	value?: GenericResponseHashMapStringString | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		data: value['data'],
		success: value['success']
	};
}
