/* tslint:disable */
/* eslint-disable */
/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface StatusResponse
 */
export interface StatusResponse {
	/**
	 * The status message
	 * @type {string}
	 * @memberof StatusResponse
	 */
	message: string;
	/**
	 * The status code of the bar
	 * @type {number}
	 * @memberof StatusResponse
	 */
	status: number;
}

/**
 * Check if a given object implements the StatusResponse interface.
 */
export function instanceOfStatusResponse(value: object): value is StatusResponse {
	if (!('message' in value) || value['message'] === undefined) return false;
	if (!('status' in value) || value['status'] === undefined) return false;
	return true;
}

export function StatusResponseFromJSON(json: any): StatusResponse {
	return StatusResponseFromJSONTyped(json, false);
}

export function StatusResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): StatusResponse {
	if (json == null) {
		return json;
	}
	return {
		message: json['message'],
		status: json['status']
	};
}

export function StatusResponseToJSON(json: any): StatusResponse {
	return StatusResponseToJSONTyped(json, false);
}

export function StatusResponseToJSONTyped(
	value?: StatusResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		message: value['message'],
		status: value['status']
	};
}
