/* tslint:disable */
/* eslint-disable */
/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Shift } from './Shift';
import { ShiftFromJSON, ShiftFromJSONTyped, ShiftToJSON, ShiftToJSONTyped } from './Shift';

/**
 *
 * @export
 * @interface EventWithShifts
 */
export interface EventWithShifts {
	/**
	 * Date and time of the event
	 * @type {Date}
	 * @memberof EventWithShifts
	 */
	date: Date;
	/**
	 * Unique identifier for the event
	 * @type {string}
	 * @memberof EventWithShifts
	 */
	id: string;
	/**
	 * Name of the event
	 * @type {string}
	 * @memberof EventWithShifts
	 */
	name: string;
	/**
	 * List of shifts associated with the event
	 * @type {Array<Shift>}
	 * @memberof EventWithShifts
	 */
	shifts: Array<Shift>;
}

/**
 * Check if a given object implements the EventWithShifts interface.
 */
export function instanceOfEventWithShifts(value: object): value is EventWithShifts {
	if (!('date' in value) || value['date'] === undefined) return false;
	if (!('id' in value) || value['id'] === undefined) return false;
	if (!('name' in value) || value['name'] === undefined) return false;
	if (!('shifts' in value) || value['shifts'] === undefined) return false;
	return true;
}

export function EventWithShiftsFromJSON(json: any): EventWithShifts {
	return EventWithShiftsFromJSONTyped(json, false);
}

export function EventWithShiftsFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): EventWithShifts {
	if (json == null) {
		return json;
	}
	return {
		date: new Date(json['date']),
		id: json['id'],
		name: json['name'],
		shifts: (json['shifts'] as Array<any>).map(ShiftFromJSON)
	};
}

export function EventWithShiftsToJSON(json: any): EventWithShifts {
	return EventWithShiftsToJSONTyped(json, false);
}

export function EventWithShiftsToJSONTyped(
	value?: EventWithShifts | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		date: value['date'].toISOString(),
		id: value['id'],
		name: value['name'],
		shifts: (value['shifts'] as Array<any>).map(ShiftToJSON)
	};
}
