/* tslint:disable */
/* eslint-disable */
/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Invitation
 */
export interface Invitation {
	/**
	 *
	 * @type {Date}
	 * @memberof Invitation
	 */
	claimedAt?: Date | null;
	/**
	 *
	 * @type {Date}
	 * @memberof Invitation
	 */
	createdAt: Date;
	/**
	 *
	 * @type {string}
	 * @memberof Invitation
	 */
	email: string;
	/**
	 *
	 * @type {Date}
	 * @memberof Invitation
	 */
	expiresAt: Date;
	/**
	 *
	 * @type {string}
	 * @memberof Invitation
	 */
	id: string;
}

/**
 * Check if a given object implements the Invitation interface.
 */
export function instanceOfInvitation(value: object): value is Invitation {
	if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
	if (!('email' in value) || value['email'] === undefined) return false;
	if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
	if (!('id' in value) || value['id'] === undefined) return false;
	return true;
}

export function InvitationFromJSON(json: any): Invitation {
	return InvitationFromJSONTyped(json, false);
}

export function InvitationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Invitation {
	if (json == null) {
		return json;
	}
	return {
		claimedAt: json['claimed_at'] == null ? undefined : new Date(json['claimed_at']),
		createdAt: new Date(json['created_at']),
		email: json['email'],
		expiresAt: new Date(json['expires_at']),
		id: json['id']
	};
}

export function InvitationToJSON(json: any): Invitation {
	return InvitationToJSONTyped(json, false);
}

export function InvitationToJSONTyped(
	value?: Invitation | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		claimed_at: value['claimedAt'] === null ? null : (value['claimedAt'] as any)?.toISOString(),
		created_at: value['createdAt'].toISOString(),
		email: value['email'],
		expires_at: value['expiresAt'].toISOString(),
		id: value['id']
	};
}
