/* tslint:disable */
/* eslint-disable */
/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface NewInvitationInput
 */
export interface NewInvitationInput {
	/**
	 * The email address to which the invitation will be sent
	 * @type {string}
	 * @memberof NewInvitationInput
	 */
	email: string;
}

/**
 * Check if a given object implements the NewInvitationInput interface.
 */
export function instanceOfNewInvitationInput(value: object): value is NewInvitationInput {
	if (!('email' in value) || value['email'] === undefined) return false;
	return true;
}

export function NewInvitationInputFromJSON(json: any): NewInvitationInput {
	return NewInvitationInputFromJSONTyped(json, false);
}

export function NewInvitationInputFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): NewInvitationInput {
	if (json == null) {
		return json;
	}
	return {
		email: json['email']
	};
}

export function NewInvitationInputToJSON(json: any): NewInvitationInput {
	return NewInvitationInputToJSONTyped(json, false);
}

export function NewInvitationInputToJSONTyped(
	value?: NewInvitationInput | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		email: value['email']
	};
}
