/* tslint:disable */
/* eslint-disable */
/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface NewShiftInput
 */
export interface NewShiftInput {
	/**
	 * End time of the shift
	 * @type {Date}
	 * @memberof NewShiftInput
	 */
	endAt: Date;
	/**
	 * Start time of the shift
	 * @type {Date}
	 * @memberof NewShiftInput
	 */
	startAt: Date;
	/**
	 * List of user IDs assigned to this shift
	 * @type {Array<string>}
	 * @memberof NewShiftInput
	 */
	userIds: Array<string>;
}

/**
 * Check if a given object implements the NewShiftInput interface.
 */
export function instanceOfNewShiftInput(value: object): value is NewShiftInput {
	if (!('endAt' in value) || value['endAt'] === undefined) return false;
	if (!('startAt' in value) || value['startAt'] === undefined) return false;
	if (!('userIds' in value) || value['userIds'] === undefined) return false;
	return true;
}

export function NewShiftInputFromJSON(json: any): NewShiftInput {
	return NewShiftInputFromJSONTyped(json, false);
}

export function NewShiftInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewShiftInput {
	if (json == null) {
		return json;
	}
	return {
		endAt: new Date(json['end_at']),
		startAt: new Date(json['start_at']),
		userIds: json['user_ids']
	};
}

export function NewShiftInputToJSON(json: any): NewShiftInput {
	return NewShiftInputToJSONTyped(json, false);
}

export function NewShiftInputToJSONTyped(
	value?: NewShiftInput | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		end_at: value['endAt'].toISOString(),
		start_at: value['startAt'].toISOString(),
		user_ids: value['userIds']
	};
}
