/* tslint:disable */
/* eslint-disable */
/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface StatusRequest
 */
export interface StatusRequest {
	/**
	 * The new status code for the bar
	 * @type {number}
	 * @memberof StatusRequest
	 */
	status: number;
}

/**
 * Check if a given object implements the StatusRequest interface.
 */
export function instanceOfStatusRequest(value: object): value is StatusRequest {
	if (!('status' in value) || value['status'] === undefined) return false;
	return true;
}

export function StatusRequestFromJSON(json: any): StatusRequest {
	return StatusRequestFromJSONTyped(json, false);
}

export function StatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusRequest {
	if (json == null) {
		return json;
	}
	return {
		status: json['status']
	};
}

export function StatusRequestToJSON(json: any): StatusRequest {
	return StatusRequestToJSONTyped(json, false);
}

export function StatusRequestToJSONTyped(
	value?: StatusRequest | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		status: value['status']
	};
}
