/* tslint:disable */
/* eslint-disable */
/**
 * api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateEventResponse
 */
export interface CreateEventResponse {
	/**
	 * Unique identifier of the created event
	 * @type {string}
	 * @memberof CreateEventResponse
	 */
	id: string;
}

/**
 * Check if a given object implements the CreateEventResponse interface.
 */
export function instanceOfCreateEventResponse(value: object): value is CreateEventResponse {
	if (!('id' in value) || value['id'] === undefined) return false;
	return true;
}

export function CreateEventResponseFromJSON(json: any): CreateEventResponse {
	return CreateEventResponseFromJSONTyped(json, false);
}

export function CreateEventResponseFromJSONTyped(
	json: any,
	ignoreDiscriminator: boolean
): CreateEventResponse {
	if (json == null) {
		return json;
	}
	return {
		id: json['id']
	};
}

export function CreateEventResponseToJSON(json: any): CreateEventResponse {
	return CreateEventResponseToJSONTyped(json, false);
}

export function CreateEventResponseToJSONTyped(
	value?: CreateEventResponse | null,
	ignoreDiscriminator: boolean = false
): any {
	if (value == null) {
		return value;
	}

	return {
		id: value['id']
	};
}
